import { GITHUB_REPOSITORY_LINK } from "./app-constant";
//
import {
  GRID_LENGTH_MINIMUM,
  GRID_LENGTH_MAXIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_MINIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_MAXIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_DEFAULT,
  NUMBER_OF_ROBOTS_MAXIMUM,
  NUMBER_OF_ROBOTS_MINIMUM,
} from "./business-constant";

export {
  GITHUB_REPOSITORY_LINK,
  //
  GRID_LENGTH_MINIMUM,
  GRID_LENGTH_MAXIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_MINIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_MAXIMUM,
  ROBOT_CLEAN_TIME_SEC_PER_CELL_DEFAULT,
  NUMBER_OF_ROBOTS_MINIMUM,
  NUMBER_OF_ROBOTS_MAXIMUM,
};
